name : Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: invoke deployment hook
      uses: distributhor/workflow-webhook@v2
      env:
        webhook url: ${{secrets.DEPLOY_HOOK_URL}}
        webhook secret: ${{secrets.DEPLOY_HOOK_KEY}}
        
    - uses: bounceapp/render-action@0.6.0
      with:
        render-token: ${{secrets.RENDER_API_KEY}}
        github-token: ${{secrets.ACC_API_KEY}}
        service-id: "39624202"
        retries: 20
        wait: 16000
        sleep: 30000
